# Generated by Django 3.0.7 on 2020-08-16 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headquarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of the headquarter')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of the movie')),
                ('duration', models.DurationField(verbose_name='duration of the movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='name of the movie genre')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of the room')),
                ('headquarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='movies.Headquarter', verbose_name='headqwuarter where the room belongs')),
            ],
        ),
        migrations.CreateModel(
            name='SpotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of the spot type')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('value', models.FloatField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spots', to='movies.Room', verbose_name='room of the spot')),
                ('spot_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.SpotType', verbose_name='spot type')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of the show')),
                ('start', models.DateTimeField(verbose_name='start date of show')),
                ('end', models.DateTimeField(verbose_name='end date of show')),
                ('scoring', models.PositiveIntegerField(verbose_name='scoring of the show')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.Movie', verbose_name='movie of the show')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.Room', verbose_name='room of the show')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movies.MovieGenre', verbose_name='genre of the movie'),
        ),
    ]
