# Generated by Django 3.0.7 on 2020-08-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spottype',
            name='value',
        ),
    ]
